
  
 export const ADD_COUPON_REQUEST='ADD_COUPON_REQUEST'
 export const ADD_COUPON_SUCCESS='ADD_COUPON_SUCCESS'
 export const ADD_COUPON_FAIL='ADD_COUPON_FAIL'


 export const GETALL_COUPON_REQUEST='GETALL_COUPON_REQUEST'
 export const GETALL_COUPON_SUCCESS='GETALL_COUPON_SUCCESS'
 export const GETALL_COUPON_FAIL='GETALL_COUPON_FAIL'

 export const DELETE_COUPON_REQUEST='DELETE_COUPON_REQUEST'
 export const DELETE_COUPON_SUCCESS='DELETE_COUPON_SUCCESS'
 export const DELETE_COUPON_FAIL='DELETE_COUPON_FAIL'

 export const GET_COUPON_REQUEST='GET_COUPON_REQUEST'
 export const GET_COUPON_SUCCESS='GET_COUPON_SUCCESS'
 export const GET_COUPON_FAIL='GET_COUPON_FAIL'


 export const APPLY_COUPON_REQUEST = 'APPLY_COUPON_REQUEST'
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS'
export const APPLY_COUPON_FAIL = 'APPLY_COUPON_FAIL'
  