export const ORDER_CREATE_REQUEST="ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS="ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAILURE="ORDER_CREATE_FAILURE"


export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAILURE="ORDER_DETAILS_FAILURE"

export const ORDER_PAY_REQUEST="ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS="ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAILURE="ORDER_PAY_FAILURE"
export const ORDER_PAY_RESET="ORDER_PAY_RESET"

export const MYORDER_LIST_REQUEST="MYORDER_LIST_REQUEST"
export const MYORDER_LIST_SUCCESS="MYORDER_LIST_SUCCESS"
export const MYORDER_LIST_FAILURE="MYORDER_LIST_FAILURE"
export const MYORDER_LIST_RESET="MYORDER_LIST_RESET"

export const ALL_ORDER_LIST_REQUEST="ALL_ORDER_LIST_REQUEST"
export const ALL_ORDER_LIST_SUCCESS="ALL_ORDER_LIST_SUCCESS"
export const ALL_ORDER_LIST_FAILURE="ALL_ORDER_LIST_FAILURE"


export const ORDER_DELIVER_REQUEST="ORDER_DELIVER_REQUEST"
export const ORDER_DELIVER_SUCCESS="ORDER_DELIVER_SUCCESS"
export const ORDER_DELIVER_FAILURE="ORDER_DELIVER_FAILURE"
export const ORDER_DELIVER_RESET="ORDER_DELIVER_RESET"


